# Generated by Django 4.2.7 on 2023-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_food_id_alter_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='food_image',
        ),
        migrations.AddField(
            model_name='food',
            name='matching_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='food',
            name='similar_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
