# Generated by Django 4.2.1 on 2023-11-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_rename_image_food_food_image_food_matching_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_image',
            new_name='food1_image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='similar_image',
            new_name='food2_image',
        ),
        migrations.AlterField(
            model_name='food',
            name='matching_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
