# Generated by Django 4.2.1 on 2023-11-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_rename_food_image_food_food1_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food1_image',
            new_name='food_image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food2_image',
        ),
    ]
