# Generated by Django 4.2.1 on 2023-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_rename_food1_image_food_food_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
